name = "shittyads"
main = "src/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "shittyads"

# Upload-Schutz setzen via: wrangler secret put UPLOAD_SECRET
